spring:
  main:
    banner-mode: off

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

logging:
  level:
    root: info