spring:
  main:
    banner-mode: off

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

  sql:
    init:
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql
      mode: always


server:
  port: 8081